import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Image from "next/image"; 
import samra from "../../../public/samra2.jpeg"
import bg from "../../../public/bg.jpg"
import { Header } from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="h-screen bg-cover bg-center bg-fixed overflow-y-auto fixed top-0 left-0 w-full"
          style={{
            backgroundImage: `url(${bg.src})`,
          }}
        >
          <Header />

          <div className="flex min-h-[90vh] flex-col md:flex-row items-center justify-center">
            {/* Left Image Section */}
            <div className="mt-8 md:mt-0 px-5 md:px-3 w-full md:w-1/2 md:h-full flex items-center justify-center ">
              <Image
                src={samra}
                alt="Samra Bano"
                className="h-[60vh] md:h-[80vh] rounded-[20px] object-contain  "
              />
            </div>

            {/* Right Text Section */}
            <div className="  w-full md:w-1/2 h-full flex flex-col justify-center items-start px-6 md:px-12 py-8 space-y-4">

              {children}

            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
