import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import samra from "../../../public/samra2.jpeg"
import bg from "../../../public/bg.jpg"
import { Header } from "../components/Header";
import { Download } from "lucide-react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div
                    className="h-screen bg-cover bg-center bg-fixed overflow-y-auto fixed top-0 left-0 w-full"
                    style={{
                        backgroundImage: `url(${bg.src})`,
                    }}
                >
                    <Header />

                    <div className="flex min-h-[90vh] flex-col md:flex-row items-center justify-center">
                        {/* Left Image Section */}
                        <div className=" flex-col gap-5 mt-8 md:mt-0 px-5 md:px-3 w-full md:w-1/2 md:h-full flex items-center justify-center ">
                            <Image
                                src={samra}
                                alt="Samra Bano"
                                className="h-[60vh] md:h-[70vh] rounded-[20px] object-contain  "
                            />

                            <a
                                href="/Samra%20Bano.pdf"
                                download
                                target="_blank"
                                rel="noopener noreferrer"

                                className="group relative inline-flex items-center gap-2 px-6 py-3 rounded-full font-semibold text-white bg-gradient-to-r from-purple-500 via-pink-500 to-yellow-500 shadow-lg shadow-pink-200 transition-all duration-300 hover:from-yellow-500 hover:via-pink-500 hover:to-purple-500 hover:scale-105 focus:outline-none overflow-hidden">
                                <span className="absolute inset-0 rounded-full opacity-20 group-hover:opacity-30 bg-white blur-sm transition-all duration-300"></span>
                                <Download className="w-5 h-5 z-10" />
                                <span className="z-10">Download CV</span>
                            </a>
                        </div>

                        {/* Right Text Section */}
                        <div className="  w-full md:w-1/2 h-full flex flex-col justify-center items-start px-6 md:px-12 py-8 space-y-4">

                            {children}

                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
